//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Special Character.
        /// </summary>
        public static string APP_BlockSpecialCharacter {
            get {
                return ResourceManager.GetString("APP_BlockSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Whitespace.
        /// </summary>
        public static string APP_BlockWhitespace {
            get {
                return ResourceManager.GetString("APP_BlockWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Details.
        /// </summary>
        public static string APP_CMN_Authentication_Details {
            get {
                return ResourceManager.GetString("APP_CMN_Authentication_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string APP_Code {
            get {
                return ResourceManager.GetString("APP_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string APP_DataType {
            get {
                return ResourceManager.GetString("APP_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        public static string APP_DateFormat {
            get {
                return ResourceManager.GetString("APP_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string APP_Description {
            get {
                return ResourceManager.GetString("APP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        public static string APP_DisplayName {
            get {
                return ResourceManager.GetString("APP_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Level Configuration.
        /// </summary>
        public static string APP_FieldLevelConfig {
            get {
                return ResourceManager.GetString("APP_FieldLevelConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name.
        /// </summary>
        public static string APP_FieldName {
            get {
                return ResourceManager.GetString("APP_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAlphanumeric.
        /// </summary>
        public static string APP_ISAlphanumeric {
            get {
                return ResourceManager.GetString("APP_ISAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAmount.
        /// </summary>
        public static string APP_IsAmount {
            get {
                return ResourceManager.GetString("APP_IsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Component.
        /// </summary>
        public static string APP_IsComponent {
            get {
                return ResourceManager.GetString("APP_IsComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInteger.
        /// </summary>
        public static string APP_IsInteger {
            get {
                return ResourceManager.GetString("APP_IsInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsMandatory.
        /// </summary>
        public static string APP_IsMandatory {
            get {
                return ResourceManager.GetString("APP_IsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Values.
        /// </summary>
        public static string APP_LOV {
            get {
                return ResourceManager.GetString("APP_LOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length.
        /// </summary>
        public static string APP_MaxLength {
            get {
                return ResourceManager.GetString("APP_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string APP_Menu {
            get {
                return ResourceManager.GetString("APP_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name.
        /// </summary>
        public static string APP_MenuName {
            get {
                return ResourceManager.GetString("APP_MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Length.
        /// </summary>
        public static string APP_MinLength {
            get {
                return ResourceManager.GetString("APP_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string APP_ORG_City {
            get {
                return ResourceManager.GetString("APP_ORG_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College Details.
        /// </summary>
        public static string APP_ORG_College_Details {
            get {
                return ResourceManager.GetString("APP_ORG_College_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string APP_ORG_ContactPerson {
            get {
                return ResourceManager.GetString("APP_ORG_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Details.
        /// </summary>
        public static string APP_ORG_ContactPerson_Details {
            get {
                return ResourceManager.GetString("APP_ORG_ContactPerson_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string APP_ORG_Country {
            get {
                return ResourceManager.GetString("APP_ORG_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Details.
        /// </summary>
        public static string APP_ORG_Department_Details {
            get {
                return ResourceManager.GetString("APP_ORG_Department_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        public static string APP_ORG_EmailID {
            get {
                return ResourceManager.GetString("APP_ORG_EmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaxNo.
        /// </summary>
        public static string APP_ORG_FaxNo {
            get {
                return ResourceManager.GetString("APP_ORG_FaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string APP_ORG_History {
            get {
                return ResourceManager.GetString("APP_ORG_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string APP_ORG_Logo {
            get {
                return ResourceManager.GetString("APP_ORG_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string APP_ORG_MobileNo {
            get {
                return ResourceManager.GetString("APP_ORG_MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        public static string APP_ORG_PhoneNo {
            get {
                return ResourceManager.GetString("APP_ORG_PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pincode.
        /// </summary>
        public static string APP_ORG_PinCode {
            get {
                return ResourceManager.GetString("APP_ORG_PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string APP_ORG_ProfileImage {
            get {
                return ResourceManager.GetString("APP_ORG_ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string APP_ORG_Qualification {
            get {
                return ResourceManager.GetString("APP_ORG_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string APP_ORG_ShortDescription {
            get {
                return ResourceManager.GetString("APP_ORG_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string APP_ORG_State {
            get {
                return ResourceManager.GetString("APP_ORG_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite.
        /// </summary>
        public static string APP_ORG_Website {
            get {
                return ResourceManager.GetString("APP_ORG_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string APP_Parent {
            get {
                return ResourceManager.GetString("APP_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string APP_Range {
            get {
                return ResourceManager.GetString("APP_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string APP_Reset {
            get {
                return ResourceManager.GetString("APP_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string APP_Role {
            get {
                return ResourceManager.GetString("APP_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Task Mapping.
        /// </summary>
        public static string APP_Role_Task_Mapping {
            get {
                return ResourceManager.GetString("APP_Role_Task_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string APP_Set {
            get {
                return ResourceManager.GetString("APP_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string APP_Task {
            get {
                return ResourceManager.GetString("APP_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string APP_TaskName {
            get {
                return ResourceManager.GetString("APP_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string APP_Type {
            get {
                return ResourceManager.GetString("APP_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string APP_Url {
            get {
                return ResourceManager.GetString("APP_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Email.
        /// </summary>
        public static string APP_ValidateEmail {
            get {
                return ResourceManager.GetString("APP_ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel Name.
        /// </summary>
        public static string APP_ViewModelName {
            get {
                return ResourceManager.GetString("APP_ViewModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CMN_Add {
            get {
                return ResourceManager.GetString("CMN_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully..
        /// </summary>
        public static string CMN_Added_Successfully {
            get {
                return ResourceManager.GetString("CMN_Added_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumeric.
        /// </summary>
        public static string CMN_AlphaNumeric {
            get {
                return ResourceManager.GetString("CMN_AlphaNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist..
        /// </summary>
        public static string CMN_Already_Exist {
            get {
                return ResourceManager.GetString("CMN_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount..
        /// </summary>
        public static string CMN_Amout {
            get {
                return ResourceManager.GetString("CMN_Amout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? Do you want to continue?.
        /// </summary>
        public static string CMN_Cofirm {
            get {
                return ResourceManager.GetString("CMN_Cofirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        public static string CMN_College {
            get {
                return ResourceManager.GetString("CMN_College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of .
        /// </summary>
        public static string CMN_Combination_Of {
            get {
                return ResourceManager.GetString("CMN_Combination_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date..
        /// </summary>
        public static string CMN_Date {
            get {
                return ResourceManager.GetString("CMN_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CMN_Delete {
            get {
                return ResourceManager.GetString("CMN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully..
        /// </summary>
        public static string CMN_Deleted_Successfully {
            get {
                return ResourceManager.GetString("CMN_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department .
        /// </summary>
        public static string CMN_Department {
            get {
                return ResourceManager.GetString("CMN_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string CMN_Edit {
            get {
                return ResourceManager.GetString("CMN_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email..
        /// </summary>
        public static string CMN_Email {
            get {
                return ResourceManager.GetString("CMN_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the form first..
        /// </summary>
        public static string CMN_Fill_Form {
            get {
                return ResourceManager.GetString("CMN_Fill_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer..
        /// </summary>
        public static string CMN_Integer {
            get {
                return ResourceManager.GetString("CMN_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access..
        /// </summary>
        public static string CMN_Invalid_Access {
            get {
                return ResourceManager.GetString("CMN_Invalid_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Updation..
        /// </summary>
        public static string CMN_Invalid_Update {
            get {
                return ResourceManager.GetString("CMN_Invalid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is mandatory..
        /// </summary>
        public static string CMN_Mandatory {
            get {
                return ResourceManager.GetString("CMN_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is.
        /// </summary>
        public static string CMN_MaximumLength {
            get {
                return ResourceManager.GetString("CMN_MaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length is.
        /// </summary>
        public static string CMN_MinimumLength {
            get {
                return ResourceManager.GetString("CMN_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need selection..
        /// </summary>
        public static string CMN_Need_Selection {
            get {
                return ResourceManager.GetString("CMN_Need_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Configuration found.
        /// </summary>
        public static string CMN_NoConfigFound {
            get {
                return ResourceManager.GetString("CMN_NoConfigFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No details found..
        /// </summary>
        public static string CMN_NoDetailsFound {
            get {
                return ResourceManager.GetString("CMN_NoDetailsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string CMN_PhoneNumber {
            get {
                return ResourceManager.GetString("CMN_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter.
        /// </summary>
        public static string CMN_PleaseEnter {
            get {
                return ResourceManager.GetString("CMN_PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string CMN_PleaseSelect {
            get {
                return ResourceManager.GetString("CMN_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Level.
        /// </summary>
        public static string CMN_PositionLevel {
            get {
                return ResourceManager.GetString("CMN_PositionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White space not allowed..
        /// </summary>
        public static string CMN_RemoveWhiteSpace {
            get {
                return ResourceManager.GetString("CMN_RemoveWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration reset successfully..
        /// </summary>
        public static string CMN_Reset_Successfully {
            get {
                return ResourceManager.GetString("CMN_Reset_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string CMN_Root {
            get {
                return ResourceManager.GetString("CMN_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CMN_Save {
            get {
                return ResourceManager.GetString("CMN_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully..
        /// </summary>
        public static string CMN_Saved_Successfully {
            get {
                return ResourceManager.GetString("CMN_Saved_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string CMN_Select {
            get {
                return ResourceManager.GetString("CMN_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special character not allowed..
        /// </summary>
        public static string CMN_SpecialChar_NotAllowed {
            get {
                return ResourceManager.GetString("CMN_SpecialChar_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully..
        /// </summary>
        public static string CMN_Updated_Successfully {
            get {
                return ResourceManager.GetString("CMN_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valid.
        /// </summary>
        public static string CMN_Valid {
            get {
                return ResourceManager.GetString("CMN_Valid", resourceCulture);
            }
        }
    }
}
