//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Eng() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResource.Resource_Eng", typeof(Resource_Eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CMN_Add {
            get {
                return ResourceManager.GetString("CMN_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully..
        /// </summary>
        public static string CMN_Added_Successfully {
            get {
                return ResourceManager.GetString("CMN_Added_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist..
        /// </summary>
        public static string CMN_Already_Exist {
            get {
                return ResourceManager.GetString("CMN_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? Do you want to continue?.
        /// </summary>
        public static string CMN_Cofirm {
            get {
                return ResourceManager.GetString("CMN_Cofirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CMN_Delete {
            get {
                return ResourceManager.GetString("CMN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully..
        /// </summary>
        public static string CMN_Deleted_Successfully {
            get {
                return ResourceManager.GetString("CMN_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string CMN_Edit {
            get {
                return ResourceManager.GetString("CMN_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access..
        /// </summary>
        public static string CMN_Invalid_Access {
            get {
                return ResourceManager.GetString("CMN_Invalid_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Updation..
        /// </summary>
        public static string CMN_Invalid_Update {
            get {
                return ResourceManager.GetString("CMN_Invalid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is mandatory..
        /// </summary>
        public static string CMN_Mandatory {
            get {
                return ResourceManager.GetString("CMN_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need selection..
        /// </summary>
        public static string CMN_Need_Selection {
            get {
                return ResourceManager.GetString("CMN_Need_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No details found..
        /// </summary>
        public static string CMN_NoDetailsFound {
            get {
                return ResourceManager.GetString("CMN_NoDetailsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter.
        /// </summary>
        public static string CMN_PleaseEnter {
            get {
                return ResourceManager.GetString("CMN_PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string CMN_PleaseSelect {
            get {
                return ResourceManager.GetString("CMN_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Level.
        /// </summary>
        public static string CMN_PositionLevel {
            get {
                return ResourceManager.GetString("CMN_PositionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CMN_Save {
            get {
                return ResourceManager.GetString("CMN_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string CMN_Select {
            get {
                return ResourceManager.GetString("CMN_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully..
        /// </summary>
        public static string CMN_Updated_Successfully {
            get {
                return ResourceManager.GetString("CMN_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
    }
}
